language: python
sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python3-dev # para que instale cups
      - libcups2-dev # para que instale cups

python:
  - "3.6"

env:
  global:
  - VERSION="13.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"


git:
  depth: 1

install:
  - pip install -r requirements.txt
  - git clone https://github.com/jobiols/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install --upgrade python-magic
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
