language: python
sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python3-dev # para que instale cups
      - libcups2-dev # para que instale cups

python:
  - "3.7"

env:
  global:
  - VERSION="13.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - git clone --depth=1 https://github.com/jobiols/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install --upgrade python-magic
  - travis_install_nightly
  - sed  -i  "s/'installable': True/'installable': False/" l10n_py_vat_book/__manifest__.py

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
