@startuml

' Cheques de terceros, en desarrollo...
'        ('draft', 'Draft'),
'        ('holding', 'Holding'),
'        ('deposited', 'Deposited'), -------------
'        ('selled', 'Selled'),      ----------------
'        ('delivered', 'Delivered'), [Endosado]
'        ('transfered', 'Transfered'),
'        ('reclaimed', 'Reclaimed'), ------------
'        ('withdrawed', 'Withdrawed'),
'        ('handed', 'Handed'),      -------------
'        ('rejected', 'Rejected'), --------------
'        ('debited', 'Debited'),
'        ('returned', 'Returned'), --------------
'        ('changed', 'Changed'),
'        ('cancel', 'Cancel'),

'        'holding':   ['draft', 'deposited', 'selled', 'delivered', 'transfered'],
'        'delivered': ['holding'],
'        'deposited': ['holding', 'rejected'],
'        'selled':    ['holding'],
'        'handed':    ['draft'],
'        'transfered': ['holding'],
'        'withdrawed': ['draft'],
'        'rejected':  ['delivered', 'deposited', 'selled', 'handed'],
'        'debited':   ['handed'],
'        'returned':  ['handed', 'holding'],
'        'changed':   ['handed', 'holding'],
'        'cancel':    ['draft'],
'        'reclaimed': ['rejected'],

note "Diagrama de estados de Cheques" as N1

Handed: [Entregado] El cheque se emitio y se el\nentrego en pago a un proveedor
Rejected: [Rechazado] Crea ND del proveedor
Debited: [Debitado] se deposita en banco\nAsiento: chq diferidos a cta banco.
Holding: [En Cartera] tenemos el cheque\ncomo valor en cartera.
Returned: [Devuelto] Devolvemos el cheque\nal emisor: genera NC al Cliente

[*] --> Handed : Emitir un cheque\nej. pago a proveedor
Handed --> Debited : BTN: Bank Debit
Handed --> Rejected: BNT: Supplier\nReturn/Rejection
Rejected --> [*]

[*] --> Holding: Recibir un cheque de\nterceros ej. pago de cliente
Holding --> Returned: BTN: Return\nto Customer
Returned --> [*]


Vendido: [Selled] El cheque se vendió y se\ncobró, el dinero fue a una\ncuenta de efectivo
Reclamado: [Reclaimed] Se genera una factura en borrador

Handed --> Vendido: Transferir a cuenta\nde efectivo

Vendido --> RechazoVenta : Se rechaza la venta
RechazoVenta --> Reclamado: Se reclama el cheque

@enduml
